# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

language: R
sudo: false
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
    update: true

r_github_packages:
  - r-spatial/lwgeom
  - r-spatial/sf

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
